# ----------
# Deploy variables

set(PIPELINERUNNER_DEPLOY_DIR         "/opt/${PROJECT_NAME}")
set(PIPELINERUNNER_CONFIG_DIR         "/etc/${PROJECT_NAME}")
set(PIPELINERUNNER_BIN_DEPLOY_DIR     "${PIPELINERUNNER_DEPLOY_DIR}/bin")
set(PIPELINERUNNER_LIB_DEPLOY_DIR     "${PIPELINERUNNER_DEPLOY_DIR}/lib")
set(PIPELINERUNNER_PLUGINS_DEPLOY_DIR "${PIPELINERUNNER_BIN_DEPLOY_DIR}/plugins")

set(PLT_INSTALL_EXE_DST    ${PIPELINERUNNER_BIN_DEPLOY_DIR})
set(PLT_INSTALL_LIB_DST    ${PIPELINERUNNER_LIB_DEPLOY_DIR})
set(PLT_INSTALL_PLUGIN_DST ${PIPELINERUNNER_PLUGINS_DEPLOY_DIR})

set(LIBPACK_DEPLOY_PATH       "/opt/qt-libpack/5.12.12")
set(DEB_CONFIG_FILES_DIR_PATH ${CMAKE_CURRENT_LIST_DIR}/deb)

# ----------
# Set config

set(DEFAULT_RABBIT_HOST "127.0.0.1")
set(DEFAULT_RABBIT_PORT 5672)
set(DEFAULT_RABBIT_LOGIN "guest")
set(DEFAULT_RABBIT_PASSWORD "guest")
set(DEFAULT_SUB_QUEUE_NAME "sub_queue_name")
set(DEFAULT_PUB_QUEUE_NAME "pub_queue_name")
set(DEFAULT_CONVERTER_PATH "/path/to/script.py")
set(DEFAULT_DATA_STORAGE "/mnt/storage/data")

set(CONFIG_FILE config.json)
configure_file(${DEB_CONFIG_FILES_DIR_PATH}/${CONFIG_FILE}.in ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${CONFIG_FILE} @ONLY)

# ----------
# Set control files

configure_file(${DEB_CONFIG_FILES_DIR_PATH}/postinst.in ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/postinst @ONLY)
configure_file(${DEB_CONFIG_FILES_DIR_PATH}/prerm.in    ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/prerm    @ONLY)

set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA
    ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/postinst
    ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/prerm
)

# ----------
# Set launch script

set(LAUNCH_PROJECT_FILE ${PROJECT_NAME}.sh)
configure_file(${DEB_CONFIG_FILES_DIR_PATH}/${LAUNCH_PROJECT_FILE}.in ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${LAUNCH_PROJECT_FILE} @ONLY)

# ----------
# Set qt config

set(QT_CONFIG_FILE qt.conf)
configure_file(${DEB_CONFIG_FILES_DIR_PATH}/${QT_CONFIG_FILE}.in ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${QT_CONFIG_FILE} @ONLY)

# ----------
# Set cpack config

set(CPACK_GENERATOR DEB)
set(CPACK_STRIP_FILES ON)
set(CPACK_PACKAGE_VENDOR "exelux")
set(CPACK_DEB_COMPONENT_INSTALL YES)
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "exelux")
set(CPACK_PACKAGE_NAME "${CMAKE_PROJECT_NAME}")
set(CPACK_PACKAGE_VERSION "0.0.1")
set(CPACK_DEBIAN_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_DEBIAN_PACKAGE_CONTROL_STRICT_PERMISSION TRUE)
set(CPACK_PACKAGE_DIRECTORY "${CMAKE_SOURCE_DIR}/installer")
set(CPACK_PACKAGING_INSTALL_PREFIX ${PIPELINERUNNER_DEPLOY_DIR})
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "pipelinerunner")

# ----------
# Set package name and depends

plt_set_dependency(GLOBAL DEPENDENCY "libc6")
plt_set_dependency(GLOBAL DEPENDENCY "libstdc++6")
plt_collect_deb_dependencies(DEPENDS_STRING GLOBAL RECURSIVE PEDANTIC)

set(CPACK_DEBIAN_PACKAGE_DEPENDS "${DEPENDS_STRING}")
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}_${CPACK_PACKAGE_VERSION}_${PLT_OS_NAME}_${PLT_OS_VERSION}")

# ----------
# Install components

install(FILES ${PIPELINERUNNER_SERVICE_FILE_PATH} DESTINATION ${SYSTEMD_SYSTEM_DIR})
install(FILES ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${QT_CONFIG_FILE} DESTINATION ${PIPELINERUNNER_BIN_DEPLOY_DIR})
install(FILES ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${LAUNCH_PROJECT_FILE} DESTINATION ${PIPELINERUNNER_DEPLOY_DIR})
install(FILES ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${CONFIG_FILE} DESTINATION ${PIPELINERUNNER_CONFIG_DIR})

plt_install_target(${PROJECT_NAME} EXCLUDE_EXTERNAL EXCLUDE_PLATFORM RECURSIVE)

get_all_targets(${CMAKE_CURRENT_SOURCE_DIR}/src/PipelineRunnerPlugins INSTALLED_PLUGINS)

foreach(PLUGIN IN LISTS INSTALLED_PLUGINS)
    plt_install_target(${PLUGIN} EXCLUDE_EXTERNAL EXCLUDE_PLATFORM RECURSIVE)
endforeach()

include(CPack)
